C: 2.0
num_searches: 60
num_iterations: 3
num_selfPlay_iterations: 500
num_parallel_games: 100
num_epochs: 4
batch_size: 64
temperature: 1.25
temperature_threshold: 5
dirichlet_epsilon: 0.25
dirichlet_alpha: 0.3